[package]
name = "twitch-to-speech"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]

[dependencies]
reqwest = "0.2.0"
url = "1.2.4"
rodio = "0.4.2"

[dependencies.irc]
version = "0.11.0"
default-features = false